

SELECT * FROM STUDENTS WHERE age > 21 ORDER BY age desc;

SELECT COUNT(*) FROM STUDENTS WHERE NAME LIKE '%a%';

SELECT * FROM COURSES WHERE FEES BETWEEN 2000 AND 3400 ORDER BY FEES asc;

SELECT * FROM STUDENTS WHERE active_flag = 0 AND age IS NOT NULL;


SELECT course_id, COUNT(*) AS total_group_enrollements FROM ENROLLMENTS GROUP BY course_id HAVING COUNT(*) > 1;

